language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - $HOME/vuepresscache
before_install:
  - sed -i 's/registry.npm.taobao.org/registry.npmjs.org/g' yarn.lock
script:
  - yarn vuepress build --cache $HOME/vuepresscache
  - rm -rf dist/_includes
deploy:
  provider: script
  skip_cleanup: true
  on: master
  script: bash -e ci/deploy.sh
