language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - $HOME/vuepresscache
before_install:
  - sed -i 's/registry.npm.taobao.org/registry.npmjs.org/g' yarn.lock
script:
  - yarn vuepress build --cache $HOME/vuepresscache
  - rm -rf dist/_includes
deploy:
  provider: script
  skip_cleanup: true
  if: branch == master AND type == push
  script:
    - openssl aes-256-cbc -K $encrypted_74088940e92b_key -iv $encrypted_74088940e92b_iv -in ci/deploy-key.enc -out ci/deploy-key -d
    - chmod 700 ci
    - chmod 600 ci/deploy-key
    - eval `ssh-agent -s`
    - ssh-add ci/deploy-key
    - git config user.name "bot"
    - git config user.email "root@localhost"
    - git -C dist init
    - git -C dist remote add origin git@github.com:thewakingsands/novice-network-pages.git
    - git -C dist add -A
    - git -C dist commit -m "Auto deploy by Travis CI"
    - git -C dist push -f origin master
