language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - $HOME/vuepresscache
script:
  - yarn vuepress build docs --cache $HOME/vuepresscache
  - rm -rf dist/_includes
before_deploy:
  - chmod +x ci/deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: ci/deploy.sh
